version: '2.0'
services:
  newsletterservice:
    image: newsletterservice:latest
    ports:
      - "8081:8081"

  account_db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
    volumes:
      - ./accountService/src/main/resources/db_init/:/docker-entrypoint-initdb.d

  accountservice:
    image: accountservice:latest
    ports:
      - "8080:8080"
    environment:
      - "CONFIG=ci.conf"
      - "DB_HOST=account_db"
      - "NEWSLETTER_HOST=newsletterservice"
    links:
      - "account_db"
      - "newsletterservice"

